services:      
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_MULTIPLE_DATABASES: database-identity,database-builder
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    ports:
      - 5432:5432
    restart: on-failure:3
    volumes:
       - ./docker/tests/create-multiple-databases.sh:/docker-entrypoint-initdb.d/create-multiple-databases.sh
    networks:
      - shine

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
    networks:
      - shine
      
  shine:
    image: gzp79/shine-services:test
    profiles:
      - test
    environment:
      - RUST_LOG=info,shine_identity=trace
    ports:
      - "8080:80"
      - "8443:443"
    links:
      - postgres:postgres.mockbox.com
      - redis:redis.mockbox.com
    extra_hosts:
      - mockbox.com:host-gateway
      - sandbox.com:127.0.0.1
      - web.sandbox.com:127.0.0.1
      - cloud.sandbox.com:127.0.0.1
    networks:
      - shine

networks:
  shine:
    external: true
