app = "shine-app"
primary_region = "cdg"

[http_service]
  internal_port = 80
  force_https = true
  #auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 0

[metrics]
    port = 80
    path = "/api/telemetry/metrics"
