edition = "2021" 

reorder_imports = true
#single_line_if_else = true
max_width = 120
#chain_width = 50
struct_lit_width = 30

#nightly only features
#format_macro_bodies = true
#format_macro_matchers = true