@url = http://localhost:8080

GET {{url}}/info/ready
###

GET {{url}}/tracing/config 
###

PUT {{url}}/tracing/config 
Content-Type: application/json

{
    "filter": "TRACE, shine_service=TRACE,hyper=INFO"
}
###


GET {{url}}/oauth/google/create_user
###

GET {{url}}/api/identities?count=1
###
