//@url = http://localhost:8080
@url = https://local.scytta.com/identity

GET {{url}}/info/ready
###

GET {{url}}/tracing/config 
###

PUT {{url}}/tracing/config 
Content-Type: application/json

{
    "filter": "TRACE, shine_service=TRACE,hyper=INFO"
}
###


GET {{url}}/ouath/google/login
###

GET {{url}}/api/identities?count=3
###

GET {{url}}/oauth/logout?terminate_all=true
###
