!/bin/bash

AZURE_TANENT_ID="${IDENTITY_TANENT_ID}"
AZURE_CLIENT_ID="${IDENTITY_CLIENT_ID}"
AZURE_CLIENT_SECRET="${IDENTITY_CLIENT_SECRET}"

echo $AZURE_TANENT_ID
echo $AZURE_CLIENT_ID
echo $AZURE_CLIENT_SECRET
/services/identity/shine-identity