models:
  mistral:
    model_name: "gpt2"
    max_length: 512
    temperature: 0.7
    top_p: 0.9
    do_sample: true
    device: "auto"  # "auto", "cpu", "cuda", "mps"
    
  blip:
    model_name: "Salesforce/blip2-opt-2.7b"
    max_length: 100
    temperature: 0.7
    top_p: 0.9
    do_sample: true
    device: "auto"
    
  vectorizer:
    model_name: "sentence-transformers/all-MiniLM-L6-v2"
    similarity_metric: "cosine"
    device: "auto"

generator:
  type: "placeholder"
  output_dir: "data/outputs"
  image_size: [512, 512]
  format: "PNG"
  
  # Placeholder generator specific settings
  placeholder:
    background_color: "#f0f0f0"
    text_color: "#333333"
    font_size: 24
    padding: 20

learning:
  similarity_threshold: 0.8
  blip_confidence_threshold: 0.5  # Minimum BLIP confidence to proceed with similarity check
  max_examples_per_rule: 100
  min_confidence: 0.7
  learning_rate: 0.1
  batch_size: 32
  
  # Rule categories
  rules:
    - name: "object_placement"
      description: "Rules for object positioning and placement"
      weight: 1.0
    - name: "color_mapping"
      description: "Rules for color interpretation"
      weight: 1.0
    - name: "spatial_relationships"
      description: "Rules for spatial relationships between objects"
      weight: 1.0
    - name: "style_transfer"
      description: "Rules for artistic style and rendering"
      weight: 0.8

api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  workers: 1
  
  # Rate limiting
  rate_limit:
    requests_per_minute: 60
    burst_size: 10

logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/generative_ai.log"
  max_size: "10MB"
  backup_count: 5

data:
  examples_dir: "data/examples"
  rules_dir: "data/rules"
  outputs_dir: "data/outputs"
  cache_dir: "data/cache"
  
  # Data retention
  max_examples_age_days: 30
  max_outputs_age_days: 7
  cleanup_interval_hours: 24

# DSL (Domain Specific Language) configuration
dsl:
  commands:
    - name: "draw_rect"
      description: "Draw an unfilled rectangle with specified parameters"
      parameters: ["x", "y", "width", "height", "color"]
    - name: "fill_rect"
      description: "Draw a filled rectangle with specified parameters"
      parameters: ["x", "y", "width", "height", "color"]
    - name: "draw_circle"
      description: "Draw an unfilled circle with specified parameters"
      parameters: ["x", "y", "radius", "color"]
    - name: "fill_circle"
      description: "Draw a filled circle with specified parameters"
      parameters: ["x", "y", "radius", "color"]
    - name: "draw_ellipse"
      description: "Draw an unfilled ellipse with specified parameters"
      parameters: ["x", "y", "width", "height", "color"]
    - name: "fill_ellipse"
      description: "Draw a filled ellipse with specified parameters"
      parameters: ["x", "y", "width", "height", "color"]
    - name: "draw_line"
      description: "Draw a line between two points"
      parameters: ["x1", "y1", "x2", "y2", "color", "width"]
    - name: "draw_text"
      description: "Draw text with specified parameters"
      parameters: ["x", "y", "text", "font_size", "color"]
    - name: "set_background"
      description: "Set the background color"
      parameters: ["color"]

# Performance and optimization
performance:
  use_cache: true
  cache_size: 1000
  parallel_processing: true
  max_workers: 4
  
  # Memory management
  max_memory_usage_gb: 8
  cleanup_threshold: 0.8 