mod guest_login;
pub use self::guest_login::*;
mod token_login;
pub use self::token_login::*;
mod oauth2_login;
pub use self::oauth2_login::*;
mod oauth2_link;
pub use self::oauth2_link::*;
mod oauth2_auth;
pub use self::oauth2_auth::*;
mod oidc_login;
pub use self::oidc_login::*;
mod oidc_link;
pub use self::oidc_link::*;
mod oidc_auth;
pub use self::oidc_auth::*;

mod logout;
pub use self::logout::*;
mod validate;
pub use self::validate::*;
mod delete_user;
pub use self::delete_user::*;
