@url = https://local.scytta.com/identity
//@url = https://cloud.scytta.com/identity

GET {{url}}/api/identities
###

GET {{url}}/api/identities/123/roles
###

PUT {{url}}/api/identities/123/roles
Content-Type: application/json

{
    "role": "UserAdmin" 
}
###
