@url = https://local.scytta.com/identity
//@url = https://cloud.scytta.com/identity

GET {{url}}/info/ready
###

GET {{url}}/api/health
###

GET {{url}}/api/tracing/config 
###

PUT {{url}}/api/tracing/config 
Content-Type: application/json

{
    "filter": "INFO, shine_identity=TRACE,hyper=INFO"
}
###