services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_MULTIPLE_DATABASES: database-test,database-identity,database-builder
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      PGOPTIONS: "-c log_lock_waits=on"
      _PGOPTIONS: "-c log_lock_waits=on -c deadlock_timeout=1s"
    ports:
      - 25432:5432
    restart: on-failure:3
    volumes:
      - ./docker/utils/create-multiple-databases.sh:/docker-entrypoint-initdb.d/create-multiple-databases.sh
    networks:
      - shine

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 26379:6379
    networks:
      - shine

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.9.0
    command: ["-config", "/config/toxiproxy.json", "-host", "0.0.0.0"]
    ports:
      - 8474:8474  # API port
      - 5432:5432  # PostgreSQL proxy
      - 6379:6379  # Redis proxy
    volumes:
      - ./docker/toxiproxy/toxiproxy.json:/config/toxiproxy.json:ro
    networks:
      - shine

  shine:
    image: gzp79/shine-services:test
    profiles:
      - test
    environment:
      - RUST_LOG=info,shine_identity=trace
    ports:
      - "8080:80"
      - "8443:443"
      - "9464:9464"
    links:
      - toxiproxy:postgres.mockbox.com
      - toxiproxy:redis.mockbox.com
    extra_hosts:
      - mockbox.com:host-gateway
      - local.scytta.com:127.0.0.1
      - cloud.local.scytta.com:127.0.0.1
    networks:
      - shine

networks:
  shine:
    external: true
