//@url = https://cloud.local.scytta.com:8443
//@url = http://cloud.local.scytta.com:8080/identity
@url = https://cloud.local.scytta.com:8443/identity
//@url = https://cloud.scytta.com/identity

@metirc_url = https://cloud.local.scytta.com:9464

GET {{url}}/../ping
###

GET {{url}}/info/ready
###

GET {{url}}/doc/openapi.json
###

GET {{url}}/api/telemetry/status
###

GET {{url}}/api/telemetry/config 
###

PUT {{url}}/api/telemetry/config 
Content-Type: application/json

{
    "filter": "TRACE, shine_identity=TRACE,hyper=INFO"
}
###

GET https://cloud.local.scytta.com:8443/ping
###

GET http://cloud.local.scytta.com:9464/metrics
###
