@url = https://cloud.local-scytta.com:7080/identity
//@url = https://cloud.scytta.com/identity

GET {{url}}/api/identities?count=100
###

GET {{url}}/api/auth/user/info
###

@userId = 69f8f210-83d8-4c58-b1b9-f482ab86b271
//@userId = 2ff2642d-4393-4833-b475-5f297e92abec

GET {{url}}/api/identities/{{userId}}/roles
Authorization: Bearer 2vazg4Rwe2uKkHABcbL8WdEAbqvPA49M
###

PUT {{url}}/api/identities/{{userId}}/roles
Authorization: Bearer 2vazg4Rwe2uKkHABcbL8WdEAbqvPA49M
Content-Type: application/json

{
    "role": "UserAdmin" 
}
###

DELETE {{url}}/api/identities/{{userId}}/roles
Authorization: Bearer 2vazg4Rwe2uKkHABcbL8WdEAbqvPA49M
Content-Type: application/json

{
    "role": "UserAdmin" 
}
###