//@url = https://cloud.sandbox.com:7080/identity
@url = https://cloud.scytta.com/identity

GET {{url}}/api/auth/providers 
###


##########################################################
// Login, logout
GET {{url}}/auth/token/login?rememberMe=true
###

GET {{url}}/auth/token/login
Authorization: Bearer 531fd7448dcc58d30122e054e2ad3f01
###

GET {{url}}/auth/logout
###

GET {{url}}/auth/logout?terminateAll=true
###

GET {{url}}/auth/validate
### 

GET {{url}}/api/auth/user/info
###

##########################################################
// 3rd party login
GET {{url}}/auth/google/login
###


##########################################################
// Sessions
GET {{url}}/api/auth/user/sessions
###

##########################################################
// Tokens
GET {{url}}/api/auth/user/tokens
###

POST {{url}}/api/auth/user/tokens
Content-Type: application/json

{
    "kind": "access",
    "timeToLive": 3000000000,
    "bindToSite": false
}
###

@token = 2e2c2993b50a69de42a29eccb14ab8f5fceeea1981cbb9b6f01f6dee6914e3df

GET {{url}}/api/auth/user/tokens/{{token}}
###

DELETE {{url}}/api/auth/user/tokens/{{token}}
###

##########################################################
// Links

GET {{url}}/api/auth/user/links
###

@provider = aa
@providerId = bb

DELETE {{url}}/api/auth/user/links/{{provider}}/{{providerId}}
###
