@url = https://cloud.sandbox.com:7080/identity
//@url = https://cloud.scytta.com/identity

GET {{url}}/api/auth/providers 
###


##########################################################
// Login, logout
GET {{url}}/auth/token/login?rememberMe=true
###

GET {{url}}/auth/token/login
Authorization: Bearer 531fd7448dcc58d30122e054e2ad3f01
###

GET {{url}}/auth/logout
###

GET {{url}}/auth/logout?terminateAll=true
###

GET {{url}}/auth/validate
### 

GET {{url}}/api/auth/user/info
###

##########################################################
// Sessions
GET {{url}}/api/auth/user/sessions
###

##########################################################
// Tokens
GET {{url}}/api/auth/user/tokens
###

@token = 7ed962cf3adc3086259a9053e59c9f13a6f919da656c93c0dace3bd3710578a3

GET {{url}}/api/auth/user/tokens/{{token}}
###

DELETE {{url}}/api/auth/user/tokens/{{token}}
###

##########################################################
// Links

GET {{url}}/api/auth/user/links
###

@provider = 7ed962cf3adc3086259a9053e59c9f13a6f919da656c93c0dace3bd3710578a3
@providerId = 7ed962cf3adc3086259a9053e59c9f13a6f919da656c93c0dace3bd3710578a3

DELETE {{url}}/api/auth/user/links/{{provider}}/{{providerId}}
###
