@baseUrl = https://cloud.test.com:7080
//@baseUrl = https://cloud.scytta.com

@url = {{baseUrl}}/identity

GET {{baseUrl}}/info/ready
###

GET {{url}}/api/health
###

GET {{url}}/api/tracing/config 
###

PUT {{url}}/api/tracing/config 
Content-Type: application/json

{
    "filter": "TRACE, shine_identity=TRACE,hyper=INFO"
}
###