@url = http://cloud.scytta-test.com:7080/identity
//@url = https://cloud.scytta.com/identity

GET {{url}}/info/ready
###

GET {{url}}/api/health
###

GET {{url}}/api/tracing/config 
###

PUT {{url}}/api/tracing/config 
Content-Type: application/json

{
    "filter": "TRACE, shine_identity=TRACE,hyper=INFO"
}
###