@url = https://local.scytta.com/identity
//@url = https://cloud.scytta.com/identity

GET {{url}}/api/identities?count=200
###

GET {{url}}/api/auth/user/info
###

GET {{url}}/api/identities/6f7c16d3-aa18-442e-9312-38acc6f4ee08/roles
###

PUT {{url}}/api/identities/6f7c16d3-aa18-442e-9312-38acc6f4ee08/roles
Content-Type: application/json

{
    "role": "UserAdmin" 
}
###


DELETE {{url}}/api/identities/6f7c16d3-aa18-442e-9312-38acc6f4ee08/roles
Content-Type: application/json

{
    "role": "UserAdmin" 
}
###