use crate::models::messages::ChatBatch;
use shine_infra::session::SessionKey;
use uuid::Uuid;

/// High level filter for messages sent to the hub bus.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum TopicKey {
    Hub,
    Chat,
}

pub trait ToTopic {
    fn topic(&self) -> TopicKey;
}

/// A lifecycle event generated by the hub itself.
#[derive(Clone, Debug)]
pub enum HubEvent {
    UserConnected {
        user_id: Uuid,
        connection_id: Uuid,
        session_key: SessionKey,
    },
    UserDisconnected {
        user_id: Uuid,
        connection_id: Uuid,
    },
    Shutdown,
}

impl ToTopic for HubEvent {
    fn topic(&self) -> TopicKey {
        TopicKey::Hub
    }
}

/// A message carried on the hub bus: a hub lifecycle event or a domain payload.
#[derive(Clone, Debug)]
pub enum HubMessage {
    Hub(HubEvent),
    Chat(ChatBatch),
}

impl ToTopic for HubMessage {
    fn topic(&self) -> TopicKey {
        match self {
            HubMessage::Hub(event) => event.topic(),
            HubMessage::Chat(batch) => batch.topic(),
        }
    }
}
