name: Cleanup Packages

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all old container versions
        uses: actions/delete-package-versions@v5
        with:
          delete-only-untagged-versions: false
          min-versions-to-keep: 3
          package-name: ${{ env.IMAGE_NAME }}
          package-type: container