name: Cleanup Packages

on:
  workflow_dispatch:

permissions:
  packages: write

env:
  REGISTRY: ghcr.io
  PACKAGE_NAME: ${{ github.event.repository.name }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all old container versions
        uses: actions/delete-package-versions@v5
        with:
          delete-only-untagged-versions: false
          min-versions-to-keep: 3
          package-name: ${{ env.PACKAGE_NAME }}
          package-type: container
